---
title: Daily Journal
---

## 24.11.2025

- Made a [pull request](https://github.com/nipreps/nipreps-book/pull/49) to the [Nipreps book repo](https://github.com/nipreps/nipreps-book)
- Realised the different DIPY tutorials
- Started reading the Nipreps book

--- 

## 25.11.2025

- Meeting with Prof. Esteban
- Prepared the DIPY development environment
  - Installation steps
    - Create a venv and source it (or use uv venv and uv pip ...)
    - To build the project
      - sudo dnf install python3-devel
      - pip install -r requirements/build.txt
      - pip install --no-build-isolation -e .
    - To build the documentation
      - pip install sphinx
      - pip install sphinx_gallery
      - pip install numpydoc
      - pip install sphinxcontrib-bibtex
      - pip install sphinx-design
      - pip install grg-sphinx-theme
    - To use the correct formatting
      - pip install --no-build-isolation -e .\[style\]
      - pip install pre-commit
      - pre-commit install
- Started to look at the current gqi predict code and pull request
- Continued reading the Nipreps book (tried to fix a latex rendering error unsuccessfully)

--- 

## 26.11.2025

- Finished reading the Nipreps book
- Continued to look at the current gqi code and made small changes on the [enh/gqi-predict-dev](https://github.com/MadeInShineA/dipy/tree/enh/gqi-predict-dev) branch
  - Changed GeneralizedQSamplingFit odf function to take a sphere parameter (see [commit](https://github.com/MadeInShineA/dipy/commit/d9ab2bd51ae442b6c106244315a8090af6ce30c4))
  - Changed the GeneralizedQSamplingFit predict function to use clamping to remove negative value predictions (see [commit](https://github.com/MadeInShineA/dipy/commit/2ff80c8add7eb7896eac8b948e2f052ac91e150d))
- Created a small [marimo](https://marimo.io/) notebook to test and understand the prediction function on the [enh/gqi-predict-notebooks](https://github.com/MadeInShineA/dipy/tree/enh/gqi-predict-notebooks) branch (see [commit](https://github.com/MadeInShineA/dipy/commit/b88191ede9cbf39a9bcd0e35c0440921034135b7))

---

## 27.11.2025

- Changed the GeneralizedQSamplingFit predict function to use the model mode when calling the predict_kernel function. Also made the predict function work for multi-voxels (see [commit](https://github.com/MadeInShineA/dipy/commit/f4e7f9b35e8efef03293bb86f40649bea517fc01))
- Started gqi predict tests with (see [commit](https://github.com/MadeInShineA/dipy/commit/f4e7f9b35e8efef03293bb86f40649bea517fc01){target="_blank"})
  - Single-voxel basic test
  - Single-voxel meaningful test
  - Multi-voxel basic test
  - Multi-voxel meaningful test
- Meeting with Prof. Esteban
- Did 2 marimo notebooks on the [enh/gqi-predict-notebooks](https://github.com/MadeInShineA/dipy/tree/enh/gqi-predict-notebooks) branch (see [commit](https://github.com/MadeInShineA/dipy/commit/0ad9d65fb0a7e4a5973afa21005b2080a60055cb){target="_blank"})
  - A notebook regarding the roundtrip predictions on already seen data (see [notebook](https://olivier.amacker.dev/303.1-semester-project/src/assets/notebooks/dipy/gqi_roundtrip_notebook.html){target="_blank"})
  - A notebook regarding cross voxel predictions (see [notebook](https://olivier.amacker.dev/303.1-semester-project/src/assets/notebooks/dipy/gqi_cross_voxel_notebook.html){target="_blank"})
- Created the 303.1-semester-project github page (see [page](https://olivier.amacker.dev/303.1-semester-project/index.html){target="_blank"})

---

## 28.11.2025

- Created the Gantt diagram
- Created the [presentation github repository](https://github.com/MadeInShineA/303.1-semester-project-presentation/tree/main){target="_blank"}(now removed)
- Started the presentation
- Published the presentation github page (see [page](https://olivier.amacker.dev/303.1-semester-project-presentation/src/presentation.html#/title-slide){target="_blank"})

---

## 01.12.2025
- Started working on the cross validation prediction test
- Worked on the project documentation (see [documentation](https://olivier.amacker.dev/303.1-semester-project/index.html){target="_blank"})
  - Added a quarto theme
  - Added sources + daily diary pages
  - Added mermaid Gantt diagram
  - Worked on the report structure (see [report](https://olivier.amacker.dev/303.1-semester-project/src/report.html){target="_blank"})

--- 

## 02.12.2025
- Added unseen data prediction tests + Cleaned gqi predict functions and existing tests (see [commit](https://github.com/MadeInShineA/dipy/commit/061896283e12e63ed326af602255ac4d8d26b4e0){target="_blank"})
- Refactored the gqi predict and prediction_kernel functions to work according to DIPY's ODF formula:\
  $ODF = S \cdot K$ (see [commit](https://github.com/MadeInShineA/dipy/commit/9b98a30292ff88e3912f9b482ba663d8f62928ca){target="_blank"})
- Wrote the The different needed helper functions and The predict function and it’s implementation sections in the [report](https://olivier.amacker.dev/303.1-semester-project/src/report.html#the-different-needed-helper-functions){target="_blank"} (see [commit](https://github.com/MadeInShineA/303.1-semester-project/commit/c3fb5235103006e8f3b1a21980b49879a6a85f69){target="_blank"})

--- 

## 03.12.2025
- Meeting with Prof. Esteban
- Started working on the unseen data prediction notebook (see [commit](https://github.com/MadeInShineA/dipy/commit/55fe6e1b9ea86a1a509b23bba3ffdf8ab77dacf0){target="_blank"})

---

## 04.12.2025
- Continued working on the unseen data prediction notebook (see [commit](https://github.com/MadeInShineA/dipy/commit/d96029289aa025db037f22727965d47d048d6a2e){target="_blank"} and [notebook](./assets/notebooks/dipy/gqi_unseen_data_notebook.html){target="_blank"})
- Began the DIPY prediction documentation example (see [commit](https://github.com/MadeInShineA/dipy/commit/f76f786770a72a642d50c752a49348f7cc728b30){target="_blank"})
- Revised predict function according to DIPY conventions (not pushed yet)

---

## 06.12.2025

- Added brain mask + interceptor + b0 volumes separation to gqi_unseen_data_notebook (see [commit](https://github.com/MadeInShineA/dipy/commit/d39f4215e5cd6348913934a00e791d25f1424c92){target="_blank"} and [notebook](./assets/notebooks/dipy/gqi_unseen_data_notebook.html){target="_blank"})
- Commented the shapes of the GeneralizedQSamplingFit predict and prediction_kernel functions (see [commit](https://github.com/MadeInShineA/dipy/commit/e78aca2e844177900aeada7ee3960f4a0cca51f4){target="_blank"})
- Optimized the predict multi voxel case a bit (see [commit](https://github.com/MadeInShineA/dipy/commit/4d6cb28cfe90938f5a2a0797abd4d3b64441f845){target="_blank"})
- Updated the [report](./report.qmd){target="_blank"}

---

## 07.12.2025
- Optimized GeneralizedQSamplingFit prediction_kernel function + Added prediction_kernel test which tests: (see [commit](https://github.com/MadeInShineA/dipy/commit/c6124414897759568ceb3e936fae93e0480e9a72){target="_blank"})
  - Correct output shape
  - K @ K_plus @ K ≈ K
  - K @ K_plus is symmetric
  - K_plus @ K is symmetric
- Made GeneralizedQSamplingFit predict function faster by fusing kernels therefore avoiding the explicit ODF calculation (see [commit](https://github.com/MadeInShineA/dipy/commit/2ef19a5a0e138bdc210821571c98afc43977f531){target="_blank"})

---

## 08.12.2025
- Continued the DIPY prediction documentation example (see [commit](https://github.com/MadeInShineA/dipy/commit/4a19e6e0a55e97cd6f6637aa7173cbccfa6f6e47){target="_blank"})

---

## 09.12.2025
- Meeting with Prof. Esteban
- Removed the gqi2 method and b0 volumes from the prediction tests (see [commit](https://github.com/MadeInShineA/dipy/commit/4ac655d547de62dadbfb4c22335788d4f3d6a216){target="_blank"})
- Removed gqi_cross_voxel_notebook + Removed b0 values from train set in gqi_roundtrip_notebook + Cleaned gqi_unseen_data_notebook (see [commit](https://github.com/MadeInShineA/dipy/commit/73c39b49fb5154f3a5b93e21e6f20547fb81c2ae){target="_blank"})

---

## 10.12.2025
- Cleaned the gqi_unseen_data_notebook (see [commit](https://github.com/MadeInShineA/dipy/commit/1ad6ce78e9d84a8363a809c5bc068885805568b3){target="_blank"})
- Continued the DIPY prediction documentation example (see [commit](https://github.com/MadeInShineA/dipy/commit/ca5e9bce3b002ba30445305341e87164760d17c0){target="_blank"} and [example](./assets/examples/reconst_gqi_predict.html){target="_blank"})

---

## 11.12.2025
- Updated README + Worked on the presentation (see [commit](https://github.com/MadeInShineA/303.1-semester-project/commit/8ac7bddc1be724c37caa5249bcd05a1b37825224){target="_blank"})

---

## 12.12.2025
- Applied the changes requested by the DIPY team on the [Prof. Esteban repository PR](https://github.com/oesteban/dipy/pull/1){target="_blank"} (see [related gqi and test_gqi commit](https://github.com/MadeInShineA/dipy/commit/0f9872ff676d85d5e89a2f2e51f672d03e5f603c){target="_blank"}, [related gqi_predict example commit](https://github.com/MadeInShineA/dipy/commit/3f6e05196749595c665275095997b9e05cc9b45e){target="_blank"} and [example](https://olivier.amacker.dev/303.1-semester-project/src/assets/examples/reconst_gqi_predict.html){target="_blank"})

--- 

## 13.12.2025
- Cleaned the GeneralizedQSamplingFit predict roundtrip tests (see [commit](https://github.com/oesteban/dipy/pull/1/commits/75cfb695ec2b5fa08f33abf963b953e7abe010af){target="_blank"})
- Began the Testing Methodology and Obtained Results sections of the report (see [report](report.qmd){target="_blank"})
- Improved marimo notebooks plot titles (see [gqi roundtrip notebook](./assets/notebooks/dipy/gqi_roundtrip_notebook.html){target="_blank"}, [gqi unseen data notebook](./assets/notebooks/dipy/gqi_unseen_data_notebook.html){target="_blank"} and [commit](https://github.com/MadeInShineA/dipy/commit/59162841d30944fea97b5779351ef2dc6a1b3d0c){target="_blank"})

---

## 14.12.2025
- Continued the report, improved the index page and added references (see [commit](https://github.com/MadeInShineA/303.1-semester-project/commit/d65df92d6120d1d6d4f7d5c76999e83ddb7865bf){target="_blank"} and [project website](./index.qmd){target="_blank"})
- Continued working on the presentation (see [commit](https://github.com/MadeInShineA/303.1-semester-project/commit/cf61234c6548e2ff0deb2f4105e3cfbf0e613d4d){target="_blank"} and [presentation](./presentation.qmd){target="_blank"})


