---
title: "Sources"
bibliography: references.bib
---

## DIPY
  - [DIPY website](https://dipy.org/){target="_blank"}
  - [DIPY github repository](https://github.com/dipy/dipy){target="_blank"}
  - [DIPY contributing guide](https://github.com/dipy/dipy/blob/master/.github/CONTRIBUTING.md){target="_blank"}
  - [DIPY developer guide](https://docs.dipy.org/stable/devel/intro.html){target="_blank"}
  - [DIPY coding style guideline](https://github.com/dipy/dipy/blob/master/doc/devel/coding_style_guideline.rst){target="_blank"}
  - Tutorials
    - [Reconstruct with Constant Solid Angle (Q-Ball)](https://docs.dipy.org/stable/examples_built/reconstruction/reconst_csa.html){target="_blank"}
    - [Reconstruct with Generalized Q-Sampling Imaging](https://docs.dipy.org/stable/examples_built/reconstruction/reconst_gqi.html){target="_blank"}
    - [Introduction to Basic Tracking](https://docs.dipy.org/stable/examples_built/fiber_tracking/tracking_introduction_eudx_1.html){target="_blank"}
    - [K-fold cross-validation for model comparison](https://docs.dipy.org/stable/examples_built/reconstruction/kfold_xval.html){target="_blank"}

---

## Youtube videos
  - [DIPY Workshop 2021 Playlist](https://www.youtube.com/playlist?list=PLRZ9VSqV-6soOC0rUEAOV-QiSa_Qxk8JM){target="_blank"}
  - [Diffusion Weighted Imaging - Doctor Klioze](https://www.youtube.com/watch?v=J_aamnpRJE8&list=LL&index=2){target="_blank"}
  - [Diffusion Tensor Imaging (DTI) - Doctor Klioze](https://www.youtube.com/watch?v=twsV81UFFcE){target="_blank"}
  - [Diffusion Tensor Imaging (DTI) Explained! | Neuroscience Methods 101 - Psyched!](https://www.youtube.com/watch?v=Be51OqnBbdc){target="_blank"}
  - [DWI vs ADC MRI sequences: EXPLAINED - Radiology Tutorials](https://www.youtube.com/watch?v=GwCRBQt2WdM){target="_blank"}
  - [Diffusion Weighted Imaging EXPLAINED (DWI Trace, ADC, B-Values) | MRI Physics Course Lecture 14 - MRI Physics EXPLAINED](https://www.youtube.com/watch?v=tcJa9cJeoEY){target="_blank"}
  - [How to Read MRI Diffusion Imaging (DWI) like a Real Radiologist - MRI Physics EXPLAINED](https://www.youtube.com/watch?v=AlhwIY0RuPc){target="_blank"}
  - [A tour of spherical harmonics-based local reconstruction techniques in DIPY - Part1 - Diffusion Imaging in Python - DIPY](https://www.youtube.com/watch?v=sTWFcfKvuIU){target="_blank"}
  - [A tour of spherical harmonics-based local reconstruction techniques in DIPY - Part2 - Diffusion Imaging in Python - DIPY](https://www.youtube.com/watch?v=SxXlckpebWQ){target="_blank"}

---

## Scientific Papers

 - @Yeh2010 
 - @Amitay2012

---

## Assistants
  - [Qwen3 Max](https://qwen.ai/home){target="_blank"}
  - [Grok Code Fast 1](https://x.ai/){target="_blank"}

## Other
  - [Nipreps book](https://github.com/nipreps/nipreps-book){target="_blank"}
  - [Prof. Esteban DIPY pull request](https://github.com/dipy/dipy/pull/3553){target="_blank"}
  - [Prof. Esteban DIPY fork](https://github.com/oesteban/dipy/tree/enh/gqi-predict){target="_blank"}
  - [Marimo website](https://marimo.io/){target="_blank"}
  - [Quarto website](https://quarto.org/){target="_blank"}
  - [Graphviz website](https://graphviz.org/){target="_blank"}
  - [Excalidraw website](https://excalidraw.com/){target="_blank"}
  - [NDMG website](https://ndmg.neurodata.io/pipeline/diffusion){target="_blank"}

## References

::: {#refs}
:::

